# Generated by Django 4.2 on 2023-04-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrivals',
        ),
    ]
