# Generated by Django 4.2 on 2023-04-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_delete_arrivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.CreateModel(
            name='Arrivals',
            fields=[
                ('arrival_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.user')),
            ],
        ),
    ]
